[package]

name = "term"
version = "0.1.13"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/term"
homepage = "https://github.com/rust-lang/term"
documentation = "http://doc.rust-lang.org/term"
description = """
A terminal formatting library
"""

[dependencies]
byteorder = "*"

[target.i686-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"
